export declare const config: import("@tamagui/core").TamaguiInternalConfig<
  Record<
    string,
    {
      [key: string]: import("@tamagui/core").VariableVal;
    }
  > & {
    color: {
      [key: string]: import("@tamagui/core").VariableVal;
    };
    space: {
      [key: string]: import("@tamagui/core").VariableVal;
    };
    size: {
      [key: string]: import("@tamagui/core").VariableVal;
    };
    radius: {
      [key: string]: import("@tamagui/core").VariableVal;
    };
    zIndex: {
      [key: string]: import("@tamagui/core").VariableVal;
    };
  },
  {
    light: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
  } & {
    light_ListItem: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Card: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Button: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Checkbox: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_DrawerFrame: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_SliderTrack: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_SliderTrackActive: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_SliderThumb: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Progress: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_ProgressIndicator: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Switch: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_SwitchThumb: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_TooltipArrow: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_TooltipContent: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Input: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_TextArea: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_Tooltip: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_SheetOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_DialogOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    light_ModalOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_ListItem: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Card: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Button: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Checkbox: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_DrawerFrame: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_SliderTrack: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_SliderTrackActive: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_SliderThumb: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Progress: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_ProgressIndicator: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Switch: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_SwitchThumb: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_TooltipArrow: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_TooltipContent: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Input: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_TextArea: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_Tooltip: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_SheetOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_DialogOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
    dark_ModalOverlay: {
      color: string;
      background: string;
      backgroundHover: string;
      backgroundPress: string;
      backgroundFocus: string;
      backgroundStrong: string;
      backgroundTransparent: string;
      colorHover: string;
      colorPress: string;
      colorFocus: string;
      colorTransparent: string;
      borderColor: string;
      borderColorHover: string;
      borderColorPress: string;
      borderColorFocus: string;
      placeholderColor: string;
      shadowColor: string;
      shadowColorHover: string;
      shadowColorPress: string;
      shadowColorFocus: string;
      color1: string;
      color2: string;
      color3: string;
      color4: string;
      color5: string;
      color6: string;
      color7: string;
      color8: string;
      color9: string;
      color10: string;
      color11: string;
      color12: string;
    };
  },
  {
    readonly ussel: "userSelect";
    readonly cur: "cursor";
    readonly pe: "pointerEvents";
    readonly col: "color";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ww: "wordWrap";
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bc: "backgroundColor";
    readonly bg: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly blc: "borderLeftColor";
    readonly blw: "borderLeftWidth";
    readonly boc: "borderColor";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly w: "width";
    readonly zi: "zIndex";
  },
  {
    [key: string]: {
      [key: string]: string | number;
    };
  },
  {
    [key: string]:
      | string
      | any[]
      | {
          [key: string]: any;
        };
  },
  import("@tamagui/core").GenericFonts,
  boolean | undefined,
  string | undefined,
  {
    allowedStyleValues?:
      | (
          | (
              | boolean
              | "strict"
              | "somewhat-strict"
              | "strict-web"
              | "somewhat-strict-web"
            )
          | {
              space?:
                | (
                    | "number"
                    | (
                        | boolean
                        | "strict"
                        | "somewhat-strict"
                        | "strict-web"
                        | "somewhat-strict-web"
                      )
                    | "percent"
                  )
                | undefined;
              size?:
                | (
                    | "number"
                    | (
                        | boolean
                        | "strict"
                        | "somewhat-strict"
                        | "strict-web"
                        | "somewhat-strict-web"
                      )
                    | "percent"
                  )
                | undefined;
              radius?:
                | (
                    | "number"
                    | (
                        | boolean
                        | "strict"
                        | "somewhat-strict"
                        | "strict-web"
                        | "somewhat-strict-web"
                      )
                  )
                | undefined;
              zIndex?:
                | (
                    | "number"
                    | (
                        | boolean
                        | "strict"
                        | "somewhat-strict"
                        | "strict-web"
                        | "somewhat-strict-web"
                      )
                  )
                | undefined;
              color?:
                | (
                    | (
                        | boolean
                        | "strict"
                        | "somewhat-strict"
                        | "strict-web"
                        | "somewhat-strict-web"
                      )
                    | "named"
                  )
                | undefined;
            }
        )
      | undefined;
    autocompleteSpecificTokens?: (boolean | "except-special") | undefined;
    mediaPropOrder?: boolean | undefined;
    fastSchemeChange?: boolean | undefined;
    webContainerType?:
      | "size"
      | "unset"
      | "normal"
      | "inline-size"
      | "inherit"
      | "initial"
      | "revert"
      | "revert-layer"
      | undefined;
  }
>;
type AppConfig = typeof config;
declare module "tamagui" {
  interface TamaguiCustomConfig extends AppConfig {}
}
export default config;
//# sourceMappingURL=tamagui.config.d.ts.map
