export declare const tokens: {
  color: {
    darkTransparent: import("@tamagui/web").Variable<string>;
    dark1: import("@tamagui/web").Variable<string>;
    dark2: import("@tamagui/web").Variable<string>;
    dark3: import("@tamagui/web").Variable<string>;
    dark4: import("@tamagui/web").Variable<string>;
    dark5: import("@tamagui/web").Variable<string>;
    dark6: import("@tamagui/web").Variable<string>;
    dark7: import("@tamagui/web").Variable<string>;
    dark8: import("@tamagui/web").Variable<string>;
    dark9: import("@tamagui/web").Variable<string>;
    dark10: import("@tamagui/web").Variable<string>;
    dark11: import("@tamagui/web").Variable<string>;
    dark12: import("@tamagui/web").Variable<string>;
    lightTransparent: import("@tamagui/web").Variable<string>;
    light1: import("@tamagui/web").Variable<string>;
    light2: import("@tamagui/web").Variable<string>;
    light3: import("@tamagui/web").Variable<string>;
    light4: import("@tamagui/web").Variable<string>;
    light5: import("@tamagui/web").Variable<string>;
    light6: import("@tamagui/web").Variable<string>;
    light7: import("@tamagui/web").Variable<string>;
    light8: import("@tamagui/web").Variable<string>;
    light9: import("@tamagui/web").Variable<string>;
    light10: import("@tamagui/web").Variable<string>;
    light11: import("@tamagui/web").Variable<string>;
    light12: import("@tamagui/web").Variable<string>;
  };
  space: {
    [x: string]: import("@tamagui/web").Variable<number>;
    [x: number]: import("@tamagui/web").Variable<number>;
    [x: symbol]: import("@tamagui/web").Variable<number>;
  };
  size: {
    0: import("@tamagui/web").Variable<number>;
    2: import("@tamagui/web").Variable<number>;
    1: import("@tamagui/web").Variable<number>;
    12: import("@tamagui/web").Variable<number>;
    14: import("@tamagui/web").Variable<number>;
    16: import("@tamagui/web").Variable<number>;
    18: import("@tamagui/web").Variable<number>;
    15: import("@tamagui/web").Variable<number>;
    17: import("@tamagui/web").Variable<number>;
    20: import("@tamagui/web").Variable<number>;
    3: import("@tamagui/web").Variable<number>;
    4: import("@tamagui/web").Variable<number>;
    5: import("@tamagui/web").Variable<number>;
    7: import("@tamagui/web").Variable<number>;
    8: import("@tamagui/web").Variable<number>;
    9: import("@tamagui/web").Variable<number>;
    10: import("@tamagui/web").Variable<number>;
    1.5: import("@tamagui/web").Variable<number>;
    6: import("@tamagui/web").Variable<number>;
    0.25: import("@tamagui/web").Variable<number>;
    0.5: import("@tamagui/web").Variable<number>;
    0.75: import("@tamagui/web").Variable<number>;
    2.5: import("@tamagui/web").Variable<number>;
    3.5: import("@tamagui/web").Variable<number>;
    true: import("@tamagui/web").Variable<number>;
    4.5: import("@tamagui/web").Variable<number>;
    5.5: import("@tamagui/web").Variable<number>;
    6.5: import("@tamagui/web").Variable<number>;
    7.6: import("@tamagui/web").Variable<number>;
    8.5: import("@tamagui/web").Variable<number>;
    9.5: import("@tamagui/web").Variable<number>;
    11: import("@tamagui/web").Variable<number>;
    13: import("@tamagui/web").Variable<number>;
    19: import("@tamagui/web").Variable<number>;
  };
  radius: {
    0: import("@tamagui/web").Variable<number>;
    2: import("@tamagui/web").Variable<number>;
    1: import("@tamagui/web").Variable<number>;
    12: import("@tamagui/web").Variable<number>;
    3: import("@tamagui/web").Variable<number>;
    4: import("@tamagui/web").Variable<number>;
    5: import("@tamagui/web").Variable<number>;
    7: import("@tamagui/web").Variable<number>;
    8: import("@tamagui/web").Variable<number>;
    9: import("@tamagui/web").Variable<number>;
    10: import("@tamagui/web").Variable<number>;
    6: import("@tamagui/web").Variable<number>;
    true: import("@tamagui/web").Variable<number>;
    11: import("@tamagui/web").Variable<number>;
  };
  zIndex: {
    0: import("@tamagui/web").Variable<number>;
    2: import("@tamagui/web").Variable<number>;
    1: import("@tamagui/web").Variable<number>;
    3: import("@tamagui/web").Variable<number>;
    4: import("@tamagui/web").Variable<number>;
    5: import("@tamagui/web").Variable<number>;
  };
} & Omit<
  {
    color: {
      darkTransparent: import("@tamagui/web").Variable<string>;
      dark1: import("@tamagui/web").Variable<string>;
      dark2: import("@tamagui/web").Variable<string>;
      dark3: import("@tamagui/web").Variable<string>;
      dark4: import("@tamagui/web").Variable<string>;
      dark5: import("@tamagui/web").Variable<string>;
      dark6: import("@tamagui/web").Variable<string>;
      dark7: import("@tamagui/web").Variable<string>;
      dark8: import("@tamagui/web").Variable<string>;
      dark9: import("@tamagui/web").Variable<string>;
      dark10: import("@tamagui/web").Variable<string>;
      dark11: import("@tamagui/web").Variable<string>;
      dark12: import("@tamagui/web").Variable<string>;
      lightTransparent: import("@tamagui/web").Variable<string>;
      light1: import("@tamagui/web").Variable<string>;
      light2: import("@tamagui/web").Variable<string>;
      light3: import("@tamagui/web").Variable<string>;
      light4: import("@tamagui/web").Variable<string>;
      light5: import("@tamagui/web").Variable<string>;
      light6: import("@tamagui/web").Variable<string>;
      light7: import("@tamagui/web").Variable<string>;
      light8: import("@tamagui/web").Variable<string>;
      light9: import("@tamagui/web").Variable<string>;
      light10: import("@tamagui/web").Variable<string>;
      light11: import("@tamagui/web").Variable<string>;
      light12: import("@tamagui/web").Variable<string>;
    };
    space: {
      [x: string]: import("@tamagui/web").Variable<any>;
      [x: number]: import("@tamagui/web").Variable<any>;
      [x: symbol]: import("@tamagui/web").Variable<any>;
    };
    size: {
      0: import("@tamagui/web").Variable<number>;
      2: import("@tamagui/web").Variable<number>;
      1: import("@tamagui/web").Variable<number>;
      12: import("@tamagui/web").Variable<number>;
      14: import("@tamagui/web").Variable<number>;
      16: import("@tamagui/web").Variable<number>;
      18: import("@tamagui/web").Variable<number>;
      15: import("@tamagui/web").Variable<number>;
      17: import("@tamagui/web").Variable<number>;
      20: import("@tamagui/web").Variable<number>;
      3: import("@tamagui/web").Variable<number>;
      4: import("@tamagui/web").Variable<number>;
      5: import("@tamagui/web").Variable<number>;
      7: import("@tamagui/web").Variable<number>;
      8: import("@tamagui/web").Variable<number>;
      9: import("@tamagui/web").Variable<number>;
      10: import("@tamagui/web").Variable<number>;
      1.5: import("@tamagui/web").Variable<number>;
      6: import("@tamagui/web").Variable<number>;
      0.25: import("@tamagui/web").Variable<number>;
      0.5: import("@tamagui/web").Variable<number>;
      0.75: import("@tamagui/web").Variable<number>;
      2.5: import("@tamagui/web").Variable<number>;
      3.5: import("@tamagui/web").Variable<number>;
      true: import("@tamagui/web").Variable<number>;
      4.5: import("@tamagui/web").Variable<number>;
      5.5: import("@tamagui/web").Variable<number>;
      6.5: import("@tamagui/web").Variable<number>;
      7.6: import("@tamagui/web").Variable<number>;
      8.5: import("@tamagui/web").Variable<number>;
      9.5: import("@tamagui/web").Variable<number>;
      11: import("@tamagui/web").Variable<number>;
      13: import("@tamagui/web").Variable<number>;
      19: import("@tamagui/web").Variable<number>;
    };
    radius: {
      0: import("@tamagui/web").Variable<number>;
      2: import("@tamagui/web").Variable<number>;
      1: import("@tamagui/web").Variable<number>;
      12: import("@tamagui/web").Variable<number>;
      3: import("@tamagui/web").Variable<number>;
      4: import("@tamagui/web").Variable<number>;
      5: import("@tamagui/web").Variable<number>;
      7: import("@tamagui/web").Variable<number>;
      8: import("@tamagui/web").Variable<number>;
      9: import("@tamagui/web").Variable<number>;
      10: import("@tamagui/web").Variable<number>;
      6: import("@tamagui/web").Variable<number>;
      true: import("@tamagui/web").Variable<number>;
      11: import("@tamagui/web").Variable<number>;
    };
    zIndex: {
      0: import("@tamagui/web").Variable<number>;
      2: import("@tamagui/web").Variable<number>;
      1: import("@tamagui/web").Variable<number>;
      3: import("@tamagui/web").Variable<number>;
      4: import("@tamagui/web").Variable<number>;
      5: import("@tamagui/web").Variable<number>;
    };
  },
  "color" | "space" | "size" | "radius" | "zIndex"
>;
//# sourceMappingURL=tokens.d.ts.map
